# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Math Modeling
author: Jiacheng Wang
copyright: "2024-2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jcwang587/math-modeling
  path_to_book: .
  branch: main 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-SXEXTGTJM7 # for google analytics

parse:
  myst_enable_extensions:
    - html_image

# Define the style of the reference labels
sphinx:
  config:
    bibtex_reference_style: author_year
    numfig: true
    numfig_secnum_depth: 1
    logo_only: false
    

launch_buttons:
  # URL for the BinderHub you want to use. This is the default.
  binderhub_url: "https://mybinder.org"
  binder: true
  colab: false
  deepnote: false
  jupyterhub: false
  thebe: true
