#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : Math Modeling
author                      : Jiacheng Wang
copyright                   : "2024-2025"
logo                        : "_static/logo.png"
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files        : false

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  

#######################################################################################
# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true

#######################################################################################
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - _bibliography/references.bib

#######################################################################################
# Information about where the book exists on the web
repository:
  url: https://github.com/jcwang587/math-modeling
  path_to_book: .
  branch: main 

#######################################################################################
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css

#######################################################################################
parse:
  myst_enable_extensions:
    - html_image

#######################################################################################
# Define the style of the reference labels
sphinx:
  config:
    bibtex_reference_style: author_year

#######################################################################################
launch_buttons:
  binderhub_url: "https://mybinder.org"
  binder: true
  notebook_interface: "jupyterlab"
  thebe: true
