# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Math Modeling
author: Jiacheng Wang
copyright: "2024-2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - _bibliography/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jcwang587/math-modeling
  path_to_book: .
  branch: main 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - html_image

# Define the style of the reference labels
sphinx:
  config:
    html_logo: "_static/logo.png"
    bibtex_reference_style: author_year

launch_buttons:
  binderhub_url: "https://mybinder.org"
  binder: true
  notebook_interface: "jupyterlab"
thebe: true

